trajectory:
  traj_init: null
  scan_consts:
    gradient_raster_time: 0.01
    gradient_mag_max: 0.04
    slew_rate_max: 0.18
    gyromagnetic_constant: 42576.0
  traj_params:
    dimension: 2
    num_shots: 32
    initialization: Random
    num_samples_per_shot: 513
    oversampling_factor: 5
    perturbation_factor: 0.75
    num_revolutions: 2
  recon_params:
    img_size: [320,320]
    FOV: [0.23,0.23]
  dist_params:
    cutoff: 25
    decay: 2
  algo_params:
    max_proj_iter: 0
    start_decim: 32
    shape_grad: null
    proj_n_cpu: 1
    stepDef: 0.009947183943243459
    proj_gpu: true
    shaking: false
    tolerance: 0
    proj_every_n_iter: 1
    remove_center_points: true
    fmm_params:
      fmm_method: gpu_direct_pykeops
acquisition:
  type: basic
reconstruction:
  type: ncpdnet
  dcomp: 1
  trainable: 1
  params:
    n_primal: 5
    three_d: false
    activation: relu
    n_iter: 10
    n_filters: 32
    normalize_image: false
    refine_smaps: true
    output_shape_spec: false
  weights_file: null
train:
  type: segmented
  segments:
  - 3
  - 2
  - 1
  optimizer:
    lr: 0.001
    loss: compound_mssim
  batch_size: 64
  num_steps_per_epoch: 10
  num_epochs: 15
  validation_steps: 1
output:
  save_freq: 50
  image_freq: 10
  grad_freq: null
  get_grads: 1
debug: 0
model_file: null
run_name: new_results
