outdir: ???
model_file: null

debug: 0
run_name: continue
defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  run:
    dir: ${oc.env:OUT_DIR}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${oc.env:OUT_DIR}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
