type: ncpdnet
dcomp: 1
trainable: 1
params:
  n_primal: 2
  three_d: true
  activation: relu
  n_iter: 12
  n_filters: 32
  normalize_image: false
  refine_smaps: false
  output_shape_spec: false
  fastmri: false
weights_file: null