type: vnet_stacked
dcomp: 1
trainable: 1
params:
  n_scales: 3
  n_filters: 16
vnet_kwargs:
  n_output_channels: 1
  kernel_size: 3 
  layers_n_non_lins: 2
  res: false
  non_linearity: relu
  dealiasing_nc: true
weights_file: null